-- Wallet users. version backs JPA optimistic locking; the CHECK is a last line of defence against overdrafts.
CREATE TABLE app_user (
    user_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100)   NOT NULL,
    upi_id       VARCHAR(100)   NOT NULL,
    balance      NUMERIC(19, 2) NOT NULL,
    phone_number VARCHAR(15),
    version      BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT uk_app_user_upi_id UNIQUE (upi_id),
    CONSTRAINT ck_app_user_balance_non_negative CHECK (balance >= 0)
);

-- Every transfer attempt: PENDING when accepted, then SUCCESS or FAILED.
-- UPI IDs are stored rather than foreign keys so that attempts to unknown UPI IDs can still be recorded.
CREATE TABLE transactions (
    transaction_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_upi_id   VARCHAR(100)   NOT NULL,
    receiver_upi_id VARCHAR(100)   NOT NULL,
    amount          NUMERIC(19, 2) NOT NULL,
    note            VARCHAR(255),
    idempotency_key VARCHAR(100),
    status          VARCHAR(20)    NOT NULL,
    failure_reason  VARCHAR(30),
    created_at      TIMESTAMP      NOT NULL,
    completed_at    TIMESTAMP,
    CONSTRAINT uk_transactions_sender_idempotency_key UNIQUE (sender_upi_id, idempotency_key),
    CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_transactions_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED'))
);

-- Statement queries filter on one side of the transfer and sort by time
CREATE INDEX idx_transactions_sender_created ON transactions (sender_upi_id, created_at);
CREATE INDEX idx_transactions_receiver_created ON transactions (receiver_upi_id, created_at);
