-- Event log of each transfer's life cycle, one row per step (case id = transaction_id).
-- This is the shape process-mining tools ingest: case id, activity, timestamp.
CREATE TABLE transaction_events (
    event_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT      NOT NULL,
    activity       VARCHAR(30) NOT NULL,
    occurred_at    TIMESTAMP   NOT NULL,
    details        VARCHAR(255),
    CONSTRAINT fk_transaction_events_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (transaction_id)
);

CREATE INDEX idx_transaction_events_transaction ON transaction_events (transaction_id, occurred_at);
CREATE INDEX idx_transaction_events_occurred ON transaction_events (occurred_at);
